CREATE TABLE CATEGORIA (
  ID INT PRIMARY KEY,
  DESCRICAO VARCHAR(100)
);


CREATE TABLE PRODUTO (
  ID INT PRIMARY KEY,
  NOME VARCHAR(100),
  VALOR DECIMAL(10,2),
  QTDE INT,
  CATEGORIA INT,
  FOREIGN KEY (CATEGORIA) REFERENCES CATEGORIA(ID)
);

create table TELEFONE (
	ID INT primary key,
	NUMERO VARCHAR(20),
	CLIENTE INT,
	FOREIGN KEY (CLIENTE) REFERENCES CLIENTE(ID)
);


create table CLIENTE (
	ID INT primary key,
	NOME VARCHAR(50),
	SEXO VARCHAR(1),
	DATA_NASC DATE,
	ENDERECO INT,
	FOREIGN KEY (ENDERECO) REFERENCES ENDERECO(ID)
);

create table ENDERECO (
	ID INT primary key,
	RUA VARCHAR (50),
	BAIRRO VARCHAR(20),
	CIDADE INT,
	FOREIGN KEY (CIDADE) REFERENCES CIDADE(ID)
);

create table CIDADE(
	ID INT primary key,
	NOME VARCHAR(50),
	UF VARCHAR (2)
);

create table VENDA(
	ID INT primary key,
	DATA_VENDA DATE,
	CLIENTE INT,
	FOREIGN KEY (CLIENTE) REFERENCES CLIENTE(ID)
);

create table VENDA_PROD (
	ID INT primary key,
	VENDA INT,
	PRODUTO INT,
	QTDE INT,
	foreign key (VENDA) references VENDA(ID),
	foreign key (PRODUTO) references PRODUTO(ID)
);

